project:
  type: website

# R, Python, and Julia code is only executed locally
execute:
  freeze: auto

website:
  title: "Daniel van Strien"
  favicon: icons/favicon.ico
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/davanstrien
      - icon: twitter
        href: https://twitter.com/vanstriendaniel

    body-footer: |
      <!-- 100% privacy-first analytics -->
      <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
      <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>

format:
  html:
    theme: cosmo
    css: styles.css
