project:
  type: website

# R, Python, and Julia code is only executed locally
execute:
  freeze: auto

website:
  title: "Daniel van Strien"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/davanstrien
      - icon: twitter
        href: https://twitter.com/vanstriendaniel
  google-analytics:
    tracking-id: "G-F61N6B5LBY"
    anonymize-ip: true
    storage: none

format:
  html:
    theme: cosmo
    css: styles.css
