project:
  type: website
execute:
  freeze: auto
website:
  title: "Daniel van Strien"
  site-url: https://danielvanstrien.xyz
  description: "Daniel van Strien's blog"
  favicon: icons/favicon.ico
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/davanstrien
      - icon: twitter
        href: https://twitter.com/vanstriendaniel
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <script defer src="https://cloud.umami.is/script.js" data-website-id="85cb27d6-dbf9-43d7-97d0-be4e6724de7a"></script>
          <meta name="msvalidate.01" content="4246174F24A3CB7C9CBEAA94E1FF8E84" />
